[package]
name    = "helloworld"
version = "0.1.0"
edition = "2024"
authors = ["kanarus <kanarus786@gmail.com>"]

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "s"
lto       = true
panic     = "abort"
